import { attribute, hashKey, table} from '@aws/dynamodb-data-mapper-annotations';

@table('music_history_dev')
export class QueryResult {
  @hashKey()
  eventID: string;
  @attribute()
  day: string;
  @attribute()
  year: number;
  @attribute()
  artist: string;
  @attribute({memberType: {type: 'String'}})
  data: Map<any, any>;
}

// @table('posts')
// class Forum {
//   @autoGeneratedHashKey()
//   id: string;
//
//   @rangeKey()
//   createdAt: Date;
// }

// export class QueryResult {
//   eventID: string;
//   day: string;
//   year: string;
//   data: Map<any, any>;
//   artist: string;
//
//   constructor(eventID: string, day: string, year: string, data: Map<any, any>, artist: string) {
//     this.eventID = eventID;
//     this.day = day;
//     this.year = year;
//     this.data = data;
//     this.artist = artist;
//   }
// }
